### ISSUE TITLE
ZHA & Zwave events not passed

### ISSUE THREAD

**Issue by kristianolofsson** [custom-components/remote_homeassistant#191]
Having all automations in the main instance it would be useful to have events passed through the API. Limitation in the API?

**Comment by McVillano** [comment]
I would like to have the events in the main instance too.

I have a second instance that only acts as a Zigbee Radio and the devices that i want to activate with the zigbee buttons are in the main instance, i cant put everything in the same instance because of space

So now i'm not capable of trigger lights in the main instance from the secondary instance, as the push events in the buttons are not passing to main instance

**Comment by kristianolofsson** [comment]
I solved my issue using nodered connected to both instances. Trigger from one and call service to the second.

**Comment by McVillano** [comment]
> I solved my issue using nodered connected to both instances. Trigger from one and call service to the second.

It's a brilliant idea!

Finally i've managed to solve it with "remote_homeassistant" but yours it's a very good workarround
