### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by Bluhme1** [custom-components/remote_homeassistant#228]
Would it be possible to “inherit” the unique_id from the slave to the master, so that you could edit the entities?

**Comment by wolverinevn** [comment]
Support unique_id property is great.

**Comment by matzzzz** [comment]
Yes, it would be great if support for unique_id was added

**Comment by XtraLarge** [comment]
Pls, it woul help so much.

**Comment by EveretteG** [comment]
I'm with all of the above! Lol. I have so many different entities coming from 6 slaves and I would like some consistency on the precision of pressures and battery levels. Some have decimals, some don't, and I can't change the precision because they do not have unique IDs. Changing the precision on the slave doesn't change it on the master either...

**Comment by FrankGiesecke** [comment]
Forwarding the unique_id would be great, because it would give the possibility to entities to areas on the master.

**Comment by asbjoern85** [comment]
It would be a huge upgrade to the awesome remote HA if this was possible. Please add this feature!

**Comment by FrankGiesecke** [comment]
A question about the unique ids:
It ist possible to configure a prefix for entities and services.
It might be a way to configure a prefix for the unique id. So you can take the unique id from the remote, prepend the prefix and we got an unique id for all remote things.

@lukas-hetzenecker  Whats your opinion abut this?

**Comment by Lk1975** [comment]
upvoting

**Comment by Lk1975** [comment]
Great Job!! Thanks
