### ISSUE TITLE
hdmi_cec service call

### ISSUE THREAD

**Issue by daandav** [custom-components/remote_homeassistant#77]
Service call from hdmi_cec integration won't get through. The switch part of the integration of the hdmi_cec works. So I can toggle the switch.hdmi_X switches, and the devices will turn on or off. However, calling for example hdmi_cec.volume service won't work. Log shows warning:
2020-12-06 21:03:47 WARNING (SyncWorker_0) [pycec] Not initialized. Waiting for init.

**Comment by postlund** [comment]
I took a stab at this and I think I know what's going on. This component listens to the events generated by a service call and verifies that `entity_id` targets an entity on the remote instance. If not, the call is discarded as it's probably to a local entity. With `hdmi_cec.volume` for instance, there's no `entity_id` as the component itself deals with the service call. So it's not possible for us to forward it to the remote host nor prevent it from reaching the local component. There might be a workaround that we can use though, I'll have a look at it later tonight as I find this use case interesting.

**Comment by daandav** [comment]
Thanks a lot for all the good work. I really like your integration! I see that a (simple) remote hdmi_cec is a frequently asked feature request. I hope you'll have some luck. If I can do anything to help (give logs, test etc.) please don't hesitate to ask.

**Comment by postlund** [comment]
So, I've managed to PoC something that works. I need to clean it up a bit and fix a few things before it's push:able, but I just wanted to give a status update.

Just to explain a bit how it will work... Due to the limitations mentioned above, it's not possible to implement this transparently. You will have to configure a "service prefix" and a "list of services to forward". Let's take your `hdmi_cec.volume` as an example. If we set the service prefix to `foobar_`, a new service called `hdmi_cec.foobar_volume` will be created that works exactly like the original one but the service call is forwarded to the remote host when it's called. This way it's possible to forward any service to the remote host.

We'll have to see when I have time to finish this, but I'll try to come up with something in the next few days or so.

**Comment by daandav** [comment]
Any luck with this? Again, if you need someone to test it just poke ;).

**Comment by postlund** [comment]
I got side-tracked with other things 😅 But I pushed #90, would be great if you could try that and let me know if it works for you.

**Comment by daandav** [comment]
So I tried this. However, it didn't do anything anymore. So I decided to do a fresh install. Erase everything in configuration.yaml and the HACS integration. However, after erasing and rebooting, at startup a message saying "Setup failed for remote_homeassistant: Integration not found. Setup.py (ERROR), Source: setup.py:138"

**Comment by postlund** [comment]
Great that you got it to work eventually. Just ping me if you find any problems.
